import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  const projectName = process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || "Kroppit";
  const embedImage = `${URL}/image.png`; // 3:2 ratio image for embeds
  const heroImage = process.env.NEXT_PUBLIC_APP_HERO_IMAGE; // For splash screen
  
  return {
    title: projectName,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    other: {
      "fc:miniapp": JSON.stringify({
        version: "1",
        imageUrl: embedImage,
        button: {
          title: `Launch ${projectName}`,
          action: {
            type: "launch_miniapp",
            splashImageUrl: heroImage,
            splashBackgroundColor: "#ffffff"
          }
        }
      }),
      "fc:frame": JSON.stringify({
        version: "1",
        imageUrl: embedImage,
        button: {
          title: `Launch ${projectName}`,
          action: {
            type: "launch_miniapp"
          }
        }
      }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
